networks:
  proxy:
    external: true # Connect to existing proxy network if available

services:
  # Frontend - Vite React app
  builderclient:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: builderclient
    command: bun run dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${DOMAIN:-http://localhost}/graphql
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.builderclient.loadbalancer.server.port=3000"
      # Main app route - serves the React app
      - "traefik.http.routers.builderclient.rule=Host(`builder.avakot.org`)" 
      - "traefik.http.routers.builderclient.entrypoints=https"
      - "traefik.http.routers.builderclient.tls=true"
      - "traefik.http.routers.builderclient.tls.certresolver=letsencrypt"
    depends_on:
      - builderserver

  # Backend - GraphQL server
  builderserver:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: builderserver
    command: bun run server
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5501
      - HOST=0.0.0.0
      - USE_ROOT_PATH=false
      - ALLOWED_ORIGIN=http://builder.avakot.org
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.builderserver.loadbalancer.server.port=5501"
      # Use the main domain with a path prefix instead of a subdomain
      - "traefik.http.routers.builderserver.rule=Host(`builder.avakot.org`) && PathPrefix(`/graphql`)"
      - "traefik.http.routers.builderserver.entrypoints=https"
      - "traefik.http.routers.builderserver.tls=true"
      - "traefik.http.routers.builderserver.tls.certresolver=letsencrypt"
